import type { Project } from "@shared/schema";

import tower1 from "@assets/stock_images/luxury_dubai_skyscra_a7d0c185.jpg";
import tower2 from "@assets/stock_images/luxury_dubai_skyscra_11762c7d.jpg";
import penthouse1 from "@assets/stock_images/luxury_penthouse_apa_9aedd515.jpg";
import penthouse2 from "@assets/stock_images/luxury_penthouse_apa_ea5e0542.jpg";
import villa1 from "@assets/stock_images/luxury_villa_pool_du_2d812c0a.jpg";
import villa2 from "@assets/stock_images/luxury_villa_pool_du_1f3f502e.jpg";
import building1 from "@assets/stock_images/modern_apartment_bui_00bba787.jpg";
import building2 from "@assets/stock_images/modern_apartment_bui_1b25c1b0.jpg";

export const sampleProjects: Project[] = [
  {
    id: "sample-1",
    slug: "marina-heights-tower",
    name: "מרינה הייטס טאואר",
    nameEn: "Marina Heights Tower",
    developer: "EMAAR",
    developerLogo: null,
    developerInfo: null,
    location: "דובאי מרינה",
    locationEn: "Dubai Marina",
    coordinates: null,
    locationDetails: null,
    priceFrom: 1250000,
    priceCurrency: "AED",
    roiPercent: 8,
    completionDate: "Q4 2025",
    propertyType: "דירה",
    buildingType: "Tower",
    bedrooms: "1-3",
    description: "מגדל יוקרה עם נוף פנורמי למרינה והים. מיקום מושלם עם גישה לחוף הים.",
    descriptionEn: "Luxury tower with panoramic views of the marina and sea. Perfect location with beach access.",
    tagline: null,
    taglineEn: null,
    imageUrl: tower1,
    heroImage: null,
    featured: true,
    status: "active",
    highlights: null,
    amenities: null,
    amenitiesByCategory: null,
    units: null,
    paymentPlan: null,
    gallery: null,
    neighborhood: null,
    floorPlans: null,
    faqs: null,
    specs: null,
    investmentMetrics: null,
    templateId: null,
    miniSiteId: null,
    prospectId: null,
    seo: null,
    views: 0,
    createdAt: null,
    updatedAt: null,
    brochureUrl: null,
    publishedAt: null,
    projectStatus: null,
    reraNumber: null,
    dldNumber: null,
    ownership: null,
    furnishing: null,
    serviceCharge: null,
    numberOfBuildings: null,
    commissionPercent: null,
    launchDate: null,
    constructionProgress: null,
    googleMapsUrl: null,
    videoUrl: null,
    tags: null,
    relatedProjects: null,
  },
  {
    id: "sample-2",
    slug: "business-bay-residence",
    name: "ביזנס ביי רזידנס",
    nameEn: "Business Bay Residence",
    developer: "DAMAC",
    developerLogo: null,
    developerInfo: null,
    location: "ביזנס ביי",
    locationEn: "Business Bay",
    coordinates: null,
    locationDetails: null,
    priceFrom: 980000,
    priceCurrency: "AED",
    roiPercent: 9,
    completionDate: "Q2 2026",
    propertyType: "דירה",
    buildingType: "Tower",
    bedrooms: "1-2",
    description: "פרויקט מודרני במרכז העסקים של דובאי. תשואה גבוהה ופוטנציאל השבחה.",
    descriptionEn: "Modern project in Dubai's business center. High yield and appreciation potential.",
    tagline: null,
    taglineEn: null,
    imageUrl: tower2,
    heroImage: null,
    featured: true,
    status: "active",
    highlights: null,
    amenities: null,
    amenitiesByCategory: null,
    units: null,
    paymentPlan: null,
    gallery: null,
    neighborhood: null,
    floorPlans: null,
    faqs: null,
    specs: null,
    investmentMetrics: null,
    templateId: null,
    miniSiteId: null,
    prospectId: null,
    seo: null,
    views: 0,
    createdAt: null,
    updatedAt: null,
    brochureUrl: null,
    publishedAt: null,
    projectStatus: null,
    reraNumber: null,
    dldNumber: null,
    ownership: null,
    furnishing: null,
    serviceCharge: null,
    numberOfBuildings: null,
    commissionPercent: null,
    launchDate: null,
    constructionProgress: null,
    googleMapsUrl: null,
    videoUrl: null,
    tags: null,
    relatedProjects: null,
  },
  {
    id: "sample-3",
    slug: "palm-penthouse-collection",
    name: "פאלם פנטהאוז קולקשן",
    nameEn: "Palm Penthouse Collection",
    developer: "NAKHEEL",
    developerLogo: null,
    developerInfo: null,
    location: "פאלם ג'ומיירה",
    locationEn: "Palm Jumeirah",
    coordinates: null,
    locationDetails: null,
    priceFrom: 4500000,
    priceCurrency: "AED",
    roiPercent: 6,
    completionDate: "מוכן",
    propertyType: "פנטהאוז",
    buildingType: "Tower",
    bedrooms: "3-4",
    description: "פנטהאוזים אקסקלוסיביים על האי הפאלם עם נוף עוצר נשימה לים ולסקייליין.",
    descriptionEn: "Exclusive penthouses on Palm Island with breathtaking sea and skyline views.",
    tagline: null,
    taglineEn: null,
    imageUrl: penthouse1,
    heroImage: null,
    featured: true,
    status: "active",
    highlights: null,
    amenities: null,
    amenitiesByCategory: null,
    units: null,
    paymentPlan: null,
    gallery: null,
    neighborhood: null,
    floorPlans: null,
    faqs: null,
    specs: null,
    investmentMetrics: null,
    templateId: null,
    miniSiteId: null,
    prospectId: null,
    seo: null,
    views: 0,
    createdAt: null,
    updatedAt: null,
    brochureUrl: null,
    publishedAt: null,
    projectStatus: null,
    reraNumber: null,
    dldNumber: null,
    ownership: null,
    furnishing: null,
    serviceCharge: null,
    numberOfBuildings: null,
    commissionPercent: null,
    launchDate: null,
    constructionProgress: null,
    googleMapsUrl: null,
    videoUrl: null,
    tags: null,
    relatedProjects: null,
  },
  {
    id: "sample-4",
    slug: "downtown-luxury-living",
    name: "דאון טאון לאקשרי ליבינג",
    nameEn: "Downtown Luxury Living",
    developer: "EMAAR",
    developerLogo: null,
    developerInfo: null,
    location: "דאון טאון",
    locationEn: "Downtown Dubai",
    coordinates: null,
    locationDetails: null,
    priceFrom: 2100000,
    priceCurrency: "AED",
    roiPercent: 7,
    completionDate: "Q1 2026",
    propertyType: "דירה",
    buildingType: "Tower",
    bedrooms: "2-3",
    description: "דירות יוקרה עם נוף לבורג' חליפה והמזרקה. חיים בלב דובאי.",
    descriptionEn: "Luxury apartments with views of Burj Khalifa and the fountain. Living in the heart of Dubai.",
    tagline: null,
    taglineEn: null,
    imageUrl: penthouse2,
    heroImage: null,
    featured: false,
    status: "active",
    highlights: null,
    amenities: null,
    amenitiesByCategory: null,
    units: null,
    paymentPlan: null,
    gallery: null,
    neighborhood: null,
    floorPlans: null,
    faqs: null,
    specs: null,
    investmentMetrics: null,
    templateId: null,
    miniSiteId: null,
    prospectId: null,
    seo: null,
    views: 0,
    createdAt: null,
    updatedAt: null,
    brochureUrl: null,
    publishedAt: null,
    projectStatus: null,
    reraNumber: null,
    dldNumber: null,
    ownership: null,
    furnishing: null,
    serviceCharge: null,
    numberOfBuildings: null,
    commissionPercent: null,
    launchDate: null,
    constructionProgress: null,
    googleMapsUrl: null,
    videoUrl: null,
    tags: null,
    relatedProjects: null,
  },
  {
    id: "sample-5",
    slug: "arabian-ranches-villa",
    name: "ערביאן ראנצ'ס וילות",
    nameEn: "Arabian Ranches Villa",
    developer: "EMAAR",
    developerLogo: null,
    developerInfo: null,
    location: "ערביאן ראנצ'ס",
    locationEn: "Arabian Ranches",
    coordinates: null,
    locationDetails: null,
    priceFrom: 3200000,
    priceCurrency: "AED",
    roiPercent: 5,
    completionDate: "מוכן",
    propertyType: "וילה",
    buildingType: "Villa",
    bedrooms: "4-5",
    description: "וילות משפחתיות מרווחות עם בריכה פרטית וגינה. קהילה סגורה עם מועדון.",
    descriptionEn: "Spacious family villas with private pool and garden. Gated community with clubhouse.",
    tagline: null,
    taglineEn: null,
    imageUrl: villa1,
    heroImage: null,
    featured: true,
    status: "active",
    highlights: null,
    amenities: null,
    amenitiesByCategory: null,
    units: null,
    paymentPlan: null,
    gallery: null,
    neighborhood: null,
    floorPlans: null,
    faqs: null,
    specs: null,
    investmentMetrics: null,
    templateId: null,
    miniSiteId: null,
    prospectId: null,
    seo: null,
    views: 0,
    createdAt: null,
    updatedAt: null,
    brochureUrl: null,
    publishedAt: null,
    projectStatus: null,
    reraNumber: null,
    dldNumber: null,
    ownership: null,
    furnishing: null,
    serviceCharge: null,
    numberOfBuildings: null,
    commissionPercent: null,
    launchDate: null,
    constructionProgress: null,
    googleMapsUrl: null,
    videoUrl: null,
    tags: null,
    relatedProjects: null,
  },
  {
    id: "sample-6",
    slug: "jvc-smart-living",
    name: "JVC סמארט ליבינג",
    nameEn: "JVC Smart Living",
    developer: "DANUBE",
    developerLogo: null,
    developerInfo: null,
    location: "JVC",
    locationEn: "Jumeirah Village Circle",
    coordinates: null,
    locationDetails: null,
    priceFrom: 650000,
    priceCurrency: "AED",
    roiPercent: 11,
    completionDate: "Q3 2025",
    propertyType: "דירה",
    buildingType: "Tower",
    bedrooms: "סטודיו-2",
    description: "דירות חכמות במחיר נגיש עם תשואה גבוהה. אידיאלי למשקיעים מתחילים.",
    descriptionEn: "Smart apartments at affordable prices with high yield. Ideal for first-time investors.",
    tagline: null,
    taglineEn: null,
    imageUrl: building1,
    heroImage: null,
    featured: false,
    status: "active",
    highlights: null,
    amenities: null,
    amenitiesByCategory: null,
    units: null,
    paymentPlan: null,
    gallery: null,
    neighborhood: null,
    floorPlans: null,
    faqs: null,
    specs: null,
    investmentMetrics: null,
    templateId: null,
    miniSiteId: null,
    prospectId: null,
    seo: null,
    views: 0,
    createdAt: null,
    updatedAt: null,
    brochureUrl: null,
    publishedAt: null,
    projectStatus: null,
    reraNumber: null,
    dldNumber: null,
    ownership: null,
    furnishing: null,
    serviceCharge: null,
    numberOfBuildings: null,
    commissionPercent: null,
    launchDate: null,
    constructionProgress: null,
    googleMapsUrl: null,
    videoUrl: null,
    tags: null,
    relatedProjects: null,
  },
  {
    id: "sample-mercedes",
    slug: "mercedes-benz-places-binghatti-city",
    name: "מרצדס-בנץ פלייסס בינגהאטי סיטי",
    nameEn: "Mercedes-Benz Places Binghatti City",
    developer: "Binghatti",
    developerLogo: null,
    developerInfo: {
      name: "Binghatti Developers",
      nameEn: "Binghatti Developers",
      description: "בינגהאטי היא אחת מחברות הנדלן המובילות בדובאי, ידועה בעיצוב חדשני ובשיתופי פעולה עם מותגי יוקרה בינלאומיים",
      descriptionEn: "Binghatti is one of Dubai leading real estate developers, known for innovative design and partnerships with international luxury brands",
      established: "2008",
      notableProjects: ["Mercedes-Benz Places Downtown", "Bugatti Residences", "Jacob & Co Residences"]
    },
    location: "נאד אל שיבא, מידאן",
    locationEn: "Nad Al Sheba, Meydan",
    coordinates: { lat: 25.1592, lng: 55.3036 },
    locationDetails: {
      area: "Nad Al Sheba",
      district: "Meydan",
      description: "מיקום אסטרטגי בלב נאד אל שיבא, סמוך למרכז מידאן ולמסלול המירוצים המפורסם",
      descriptionEn: "Strategic location in the heart of Nad Al Sheba, close to Meydan Racecourse and central Dubai",
      nearbyLandmarks: ["Meydan Racecourse", "Dubai Creek Harbour", "Downtown Dubai", "Business Bay"]
    },
    priceFrom: 1600000,
    priceCurrency: "AED",
    roiPercent: 9,
    completionDate: "2029",
    propertyType: "דירה",
    buildingType: "Tower",
    bedrooms: "סטודיו - 5 חדרים",
    description: "מרצדס-בנץ פלייסס בינגהאטי סיטי הוא פרויקט ענק בשווי 30 מיליארד דירהם, הכולל 12 מגדלים ו-13,386 יחידות דיור. הפרויקט משלב את העיצוב האייקוני של מרצדס-בנץ עם החזון הארכיטקטוני של בינגהאטי, ומציע דירות מסטודיו ועד פנטהאוזים יוקרתיים עם 5 חדרים.",
    descriptionEn: "Mercedes-Benz Places Binghatti City is a massive AED 30 billion development featuring 12 towers and 13,386 residences. The project combines Mercedes-Benz iconic design with Binghatti architectural vision, offering units from studios to 5-bedroom penthouses.",
    tagline: "מותג היוקרה הגרמני פוגש את החזון הדובאיאני",
    taglineEn: "German Luxury Meets Dubai Vision",
    imageUrl: "/projects/mercedes/exterior/25006_aerial_shot-fog-logo.webp",
    heroImage: "/projects/mercedes/exterior/25006_aerial_shot-fog-logo.webp",
    featured: true,
    status: "active",
    highlights: [
      { icon: "building", title: "12 מגדלים", titleEn: "12 Towers", value: "כולל מגדל Maybach" },
      { icon: "home", title: "13,386 יחידות", titleEn: "13,386 Units", value: "סטודיו עד 5 חדרים" },
      { icon: "ruler", title: "10 מיליון רגל רבוע", titleEn: "10M Sq Ft", value: "שטח פיתוח" },
      { icon: "calendar", title: "מסירה 2029", titleEn: "Handover 2029", value: "3.5 שנים" }
    ],
    amenities: [
      { category: "wellness", items: [{ icon: "spa", name: "Spa", nameHe: "ספא" }, { icon: "gym", name: "Fitness Center", nameHe: "חדר כושר" }] },
      { category: "lifestyle", items: [{ icon: "pool", name: "Infinity Pool", nameHe: "בריכה אינסופית" }, { icon: "concierge", name: "Concierge", nameHe: "קונסיירז" }] }
    ],
    amenitiesByCategory: null,
    units: [
      { type: "Studio", typeHe: "סטודיו", sizeFrom: 370, sizeTo: 380, priceFrom: 1600000, priceTo: 1800000, features: ["מרפסת", "נוף"] },
      { type: "1 Bedroom", typeHe: "חדר שינה אחד", sizeFrom: 600, sizeTo: 750, priceFrom: 2600000, priceTo: 3000000, features: ["מרפסת", "חניה"] },
      { type: "2 Bedroom", typeHe: "2 חדרי שינה", sizeFrom: 992, sizeTo: 1200, priceFrom: 3000000, priceTo: 4500000, features: ["2 מרפסות", "חניה כפולה"] },
      { type: "3 Bedroom", typeHe: "3 חדרי שינה", sizeFrom: 1321, sizeTo: 1600, priceFrom: 5000000, priceTo: 7000000, features: ["נוף פנורמי", "חדר שירות"] }
    ],
    paymentPlan: {
      name: "תוכנית תשלום גמישה",
      nameEn: "Flexible Payment Plan",
      downPayment: 10,
      duringConstruction: 50,
      onHandover: 40,
      milestones: [
        { percentage: 10, description: "מקדמה בהזמנה", descriptionEn: "Booking Fee" },
        { percentage: 50, description: "במהלך הבנייה", descriptionEn: "During Construction" },
        { percentage: 40, description: "במסירה", descriptionEn: "On Handover" }
      ]
    },
    gallery: [
      { url: "/projects/mercedes/exterior/25006_aerial_shot-fog-logo.webp", alt: "מבט אווירי", altEn: "Aerial View", type: "image" },
      { url: "/projects/mercedes/exterior/25006_Street_Shot.webp", alt: "מבט מהרחוב", altEn: "Street View", type: "image" },
      { url: "/projects/mercedes/exterior/250850_Binghatti_MasterCommunity_View06.webp", alt: "מבט כללי על הקהילה", altEn: "Community View", type: "image" },
      { url: "/projects/mercedes/lobby/LOBBY_DAY_REV02_01_JPEG.webp", alt: "לובי ראשי - יום", altEn: "Main Lobby - Day", type: "image" },
      { url: "/projects/mercedes/lobby/LOBBY_DUSK_REV02_01__JPEG.webp", alt: "לובי ראשי - ערב", altEn: "Main Lobby - Dusk", type: "image" },
      { url: "/projects/mercedes/living/Living__CAM01_DAY_JPEG.webp", alt: "סלון יוקרתי - יום", altEn: "Luxury Living Room - Day", type: "image" },
      { url: "/projects/mercedes/living/Living__CAM01_Night_JPEG.webp", alt: "סלון יוקרתי - לילה", altEn: "Luxury Living Room - Night", type: "image" },
      { url: "/projects/mercedes/living/Bedroom_Cam01.webp", alt: "חדר שינה מאסטר", altEn: "Master Bedroom", type: "image" },
      { url: "/projects/mercedes/kitchen/Kitchen-P1-001.webp", alt: "מטבח מעוצב", altEn: "Designer Kitchen", type: "image" },
      { url: "/projects/mercedes/kitchen/Kitchen-P1-002.webp", alt: "מטבח מודרני", altEn: "Modern Kitchen", type: "image" },
      { url: "/projects/mercedes/parking/Parking_01_2_copy.webp", alt: "חניה פרטית", altEn: "Private Parking", type: "image" },
      { url: "/projects/mercedes/exterior/25006_aerialNight_shot_-Final.webp", alt: "מבט לילי", altEn: "Night View", type: "image" }
    ],
    neighborhood: {
      description: "נאד אל שיבא היא שכונה מתפתחת במהירות בדובאי, הממוקמת סמוך למידאן ולמרכז העיר",
      descriptionEn: "Nad Al Sheba is a rapidly developing area in Dubai, located near Meydan and central Dubai",
      nearbyPlaces: [
        { name: "Meydan Racecourse", distance: "5 דקות", type: "landmark" },
        { name: "Downtown Dubai", distance: "15 דקות", type: "district" },
        { name: "Dubai Mall", distance: "20 דקות", type: "shopping" },
        { name: "Dubai International Airport", distance: "15 דקות", type: "transport" }
      ]
    },
    floorPlans: null,
    faqs: [
      { question: "האם זרים יכולים לרכוש?", questionEn: "Can foreigners purchase?", answer: "כן, 100% בעלות מלאה לזרים באזורי Freehold", answerEn: "Yes, 100% freehold ownership for foreigners" },
      { question: "מה תוכנית התשלום?", questionEn: "What is the payment plan?", answer: "10% מקדמה, 50% במהלך הבנייה, 40% במסירה", answerEn: "10% down payment, 50% during construction, 40% on handover" },
      { question: "האם הרכישה מזכה בויזת גולדן?", questionEn: "Is Golden Visa eligible?", answer: "כן, רכישה מעל 2 מיליון דירהם מזכה בויזת גולדן ל-10 שנים", answerEn: "Yes, purchases above AED 2M qualify for 10-year Golden Visa" }
    ],
    specs: {
      totalFloors: 34,
      totalUnits: 13386,
      totalParkingSpaces: 15000,
      buildingHeight: "150m",
      architecturalStyle: "Contemporary Mercedes-Benz Design"
    },
    investmentMetrics: {
      expectedRoiPercent: 9,
      rentalYieldPercent: 8,
      pricePerSqft: 1600,
      capitalAppreciationForecast: "15-20% עד 2030",
      goldenVisaEligible: true
    },
    templateId: null,
    miniSiteId: null,
    prospectId: null,
    seo: {
      title: "Mercedes-Benz Places Binghatti City | השקעות נדלן בדובאי",
      description: "פרויקט יוקרה בשיתוף מרצדס-בנץ ובינגהאטי. 12 מגדלים, 13,386 יחידות. מחירים מ-1.6 מיליון דירהם.",
      ogImage: "/projects/mercedes/exterior/25006_aerial_shot-fog-logo.webp"
    },
    views: 0,
    createdAt: null,
    updatedAt: null,
    brochureUrl: null,
    publishedAt: null,
    projectStatus: null,
    reraNumber: null,
    dldNumber: null,
    ownership: null,
    furnishing: null,
    serviceCharge: null,
    numberOfBuildings: null,
    commissionPercent: null,
    launchDate: null,
    constructionProgress: null,
    googleMapsUrl: null,
    videoUrl: null,
    tags: null,
    relatedProjects: null,
  },
];

export const projects: Project[] = [];

export const developers = [
  { name: "EMAAR", logo: "EMAAR" },
  { name: "DAMAC", logo: "DAMAC" },
  { name: "SOBHA", logo: "SOBHA" },
  { name: "NAKHEEL", logo: "NAKHEEL" },
  { name: "MERAAS", logo: "MERAAS" },
  { name: "DANUBE", logo: "DANUBE" },
  { name: "AZIZI", logo: "AZIZI" },
  { name: "ELLINGTON", logo: "ELLINGTON" },
  { name: "Binghatti", logo: "Binghatti" },
];

export const dubaiAreas = [
  {
    id: "business-bay",
    name: "ביזנס ביי",
    nameEn: "Business Bay",
    avgRoi: 7.5,
    rentalYield: 6.8,
    appreciation: 12,
    description: "מרכז עסקים מוביל עם גישה מצוינת לכל חלקי העיר",
    descriptionEn: "Leading business center with excellent access to all parts of the city",
  },
  {
    id: "dubai-marina",
    name: "דובאי מרינה",
    nameEn: "Dubai Marina",
    avgRoi: 6.5,
    rentalYield: 6.2,
    appreciation: 10,
    description: "אזור יוקרתי עם מרינה מרהיבה וחיי לילה תוססים",
    descriptionEn: "Luxury area with stunning marina and vibrant nightlife",
  },
  {
    id: "jvc",
    name: "JVC",
    nameEn: "Jumeirah Village Circle",
    avgRoi: 9.5,
    rentalYield: 8.5,
    appreciation: 15,
    description: "אזור צומח במהירות עם תשואות גבוהות ומחירי כניסה נוחים",
    descriptionEn: "Fast-growing area with high yields and affordable entry prices",
  },
  {
    id: "downtown",
    name: "דאון טאון",
    nameEn: "Downtown Dubai",
    avgRoi: 5.5,
    rentalYield: 5.0,
    appreciation: 8,
    description: "הלב הפועם של דובאי עם בורג' חליפה והמזרקה המפורסמת",
    descriptionEn: "The beating heart of Dubai with Burj Khalifa and the famous fountain",
  },
  {
    id: "palm",
    name: "פאלם ג'ומיירה",
    nameEn: "Palm Jumeirah",
    avgRoi: 5.0,
    rentalYield: 4.5,
    appreciation: 7,
    description: "האי המלאכותי המפורסם בעולם - סמל של יוקרה",
    descriptionEn: "The world-famous artificial island - a symbol of luxury",
  },
];

export const investmentSteps = [
  {
    number: 1,
    title: "שיחת היכרות",
    titleEn: "Introduction Call",
    description: "הבנת הצרכים, התקציב והמטרות שלך",
    descriptionEn: "Understanding your needs, budget, and goals",
    icon: "phone",
  },
  {
    number: 2,
    title: "ניתוח צרכים",
    titleEn: "Needs Analysis",
    description: "בניית פרופיל משקיע ואסטרטגיה מותאמת",
    descriptionEn: "Building an investor profile and tailored strategy",
    icon: "target",
  },
  {
    number: 3,
    title: "סקירת שוק",
    titleEn: "Market Review",
    description: "ניתוח מעמיק של השוק ואזורי ההשקעה",
    descriptionEn: "In-depth analysis of the market and investment areas",
    icon: "chart",
  },
  {
    number: 4,
    title: "המלצות מותאמות",
    titleEn: "Recommendations",
    description: "הצגת הזדמנויות ספציפיות למידותיך",
    descriptionEn: "Presenting specific opportunities for you",
    icon: "search",
  },
  {
    number: 5,
    title: "סיור וירטואלי",
    titleEn: "Virtual Tour",
    description: "סיור מקוון בנכסים הנבחרים",
    descriptionEn: "Online tour of selected properties",
    icon: "video",
  },
  {
    number: 6,
    title: "בדיקת יזם",
    titleEn: "Developer Check",
    description: "אימות רקע ואמינות היזם",
    descriptionEn: "Background and reliability verification",
    icon: "shield",
  },
  {
    number: 7,
    title: "ליווי משפטי",
    titleEn: "Legal Support",
    description: "בדיקת חוזים וליווי משפטי מלא",
    descriptionEn: "Contract review and full legal support",
    icon: "file-signature",
  },
  {
    number: 8,
    title: "ליווי ברכישה",
    titleEn: "Purchase Support",
    description: "ניהול מלא של תהליך הרכישה",
    descriptionEn: "Full management of the purchase process",
    icon: "handshake",
  },
  {
    number: 9,
    title: "מעקב בנייה",
    titleEn: "Construction",
    description: "עדכונים שוטפים על התקדמות הבנייה",
    descriptionEn: "Regular updates on construction progress",
    icon: "building",
  },
  {
    number: 10,
    title: "מסירה וניהול",
    titleEn: "Handover",
    description: "ליווי במסירה ובניהול הנכס",
    descriptionEn: "Support at handover and property management",
    icon: "key",
  },
];

export const whyDubaiReasons = [
  {
    title: "0% מס על נדל״ן",
    titleEn: "0% Property Tax",
    description: "ללא מס רכישה, מס שבח, או מס על הכנסות משכירות",
    descriptionEn: "No purchase tax, capital gains tax, or tax on rental income",
    icon: "percent",
  },
  {
    title: "תשואה 8-12%",
    titleEn: "8-12% Returns",
    description: "תשואות שכירות מהגבוהות בעולם בהשוואה לערים מובילות",
    descriptionEn: "Among the highest rental yields in the world compared to leading cities",
    icon: "trending-up",
  },
  {
    title: "ביטחון מוחלט",
    titleEn: "Absolute Security",
    description: "אחוזי פשיעה כמעט אפסיים - מהמדינות הבטוחות בעולם",
    descriptionEn: "Near-zero crime rates - one of the safest countries in the world",
    icon: "shield",
  },
  {
    title: "בעלות מלאה",
    titleEn: "Full Ownership",
    description: "זכויות בעלות מלאות לזרים באזורי Freehold",
    descriptionEn: "Full ownership rights for foreigners in Freehold areas",
    icon: "key",
  },
  {
    title: "תשלום מראש לשנה",
    titleEn: "Annual Prepayment",
    description: "שוכרים משלמים שנה מראש - יציבות תזרימית מיידית",
    descriptionEn: "Tenants pay a year in advance - immediate cash flow stability",
    icon: "calendar",
  },
  {
    title: "ויזת משקיע",
    titleEn: "Investor Visa",
    description: "ויזת שהייה לטווח ארוך למשקיעים בנדל״ן",
    descriptionEn: "Long-term residence visa for real estate investors",
    icon: "passport",
  },
  {
    title: "נגישות גלובלית",
    titleEn: "Global Accessibility",
    description: "מיקום אסטרטגי - 4 שעות טיסה מ-4 מיליארד אנשים",
    descriptionEn: "Strategic location - 4 hour flight from 4 billion people",
    icon: "globe",
  },
  {
    title: "הגנה ממשלתית",
    titleEn: "Government Protection",
    description: "רגולציה חזקה ומערכת משפטית שמגנה על המשקיעים",
    descriptionEn: "Strong regulation and legal system protecting investors",
    icon: "landmark",
  },
  {
    title: "מימון נוח",
    titleEn: "Easy Financing",
    description: "תוכניות תשלום גמישות ישירות מהיזמים",
    descriptionEn: "Flexible payment plans directly from developers",
    icon: "wallet",
  },
  {
    title: "שוק בצמיחה",
    titleEn: "Growing Market",
    description: "צמיחה מתמדת של 20%+ בשוק הנדל״ן בשנים האחרונות",
    descriptionEn: "Consistent 20%+ growth in real estate market in recent years",
    icon: "chart",
  },
];

export const whyDdlReasons = [
  {
    title: "סוכן מקומי בדובאי",
    description: "אנחנו חיים ופועלים מדובאי - לא שליחים מרחוק. גישה אמיתית לפרויקטים ועבודה ישירה מול קבלנים.",
    icon: "map-pin",
  },
  {
    title: "תהליך שקוף ומסודר",
    description: "5 שלבים ברורים ללא הפתעות. אנחנו מציגים את התמונה המלאה - יתרונות לצד סיכונים.",
    icon: "list-checks",
  },
  {
    title: "ללא עמלות נסתרות",
    description: "עמלות גלויות מראש. מה שסוכם - זה מה שקורה. בלי תוספות ובלי אותיות קטנות.",
    icon: "badge-check",
  },
];

export const stats = [
  { label: "פרויקטים פעילים", value: 50, suffix: "+" },
  { label: "משקיעים מרוצים", value: 200, suffix: "+" },
  { label: "תשואה ממוצעת", value: 8, suffix: "%" },
  { label: "שנות ניסיון", value: 5, suffix: "+" },
];

export const caseStudies = [
  {
    id: "1",
    investmentAmount: 800000,
    currentValue: 1120000,
    roiPercent: 40,
    investmentYear: "2022",
    exitYear: "2024",
    location: "JVC",
    locationEn: "JVC",
    type: "דירת 2 חדרים",
    typeEn: "2 Bedroom Apartment",
    testimonial: "התהליך היה מסודר ושקוף לחלוטין. קיבלתי ליווי צמוד מהרגע הראשון ועד קבלת המפתח.",
    testimonialEn: "The process was organized and completely transparent. I received close support from day one until key handover.",
  },
  {
    id: "2",
    investmentAmount: 1500000,
    currentValue: 1950000,
    roiPercent: 30,
    investmentYear: "2021",
    exitYear: "2024",
    location: "ביזנס ביי",
    locationEn: "Business Bay",
    type: "דירת 3 חדרים",
    typeEn: "3 Bedroom Apartment",
    testimonial: "השקעתי בפרויקט על הנייר וקיבלתי תשואה מעולה. ההמלצה הייתה מדויקת והתאימה בדיוק לצרכים שלי.",
    testimonialEn: "I invested in an off-plan project and received excellent returns. The recommendation was precise and perfectly matched my needs.",
  },
  {
    id: "3",
    investmentAmount: 2200000,
    currentValue: 2860000,
    roiPercent: 30,
    investmentYear: "2020",
    exitYear: "2024",
    location: "דובאי מרינה",
    locationEn: "Dubai Marina",
    type: "דירת 2 חדרים + שכירות",
    typeEn: "2 Bedroom Apartment + Rental",
    testimonial: "הנכס מניב לי הכנסה חודשית קבועה ובנוסף עלה בערכו משמעותית. השילוב המושלם.",
    testimonialEn: "The property provides me with steady monthly income and has also appreciated significantly in value. The perfect combination.",
  },
];
