import { pgTable, text, varchar, integer, boolean, timestamp, json, index } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

// =====================
// Users & Permissions
// =====================
export const users = pgTable("users", {
  id: varchar("id").primaryKey(),
  username: text("username").notNull().unique(),
  email: text("email").notNull().unique(),
  password: text("password").notNull(),
  role: text("role").default("viewer"), // admin, editor, viewer
  permissions: json("permissions"), // { pages: true, projects: true, leads: true, etc }
  lastLogin: timestamp("last_login"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const insertUserSchema = createInsertSchema(users).omit({ id: true, createdAt: true, updatedAt: true, lastLogin: true });
export type InsertUser = z.infer<typeof insertUserSchema>;
export type User = typeof users.$inferSelect;

// =====================
// Mini-Sites
// =====================
export const miniSites = pgTable("mini_sites", {
  id: varchar("id").primaryKey(),
  name: text("name").notNull(),
  slug: text("slug").notNull().unique(),
  projectId: varchar("project_id"), // Link to project if applicable
  status: text("status").default("draft"), // draft, active, hidden
  templateId: varchar("template_id"),
  // Content sections
  hero: json("hero"), // { title, subtitle, image, cta }
  about: json("about"), // { title, content, images }
  features: json("features"), // [{ icon, title, description }]
  gallery: json("gallery"), // [{ url, alt, caption }]
  pricing: json("pricing"), // { title, items: [{ name, price, details }] }
  location: json("location"), // { address, coordinates, mapEmbed }
  contact: json("contact"), // { phone, email, whatsapp, form }
  faq: json("faq"), // [{ question, answer }]
  // AI-Classified images manifest (section-bound images from PDF)
  imageManifest: json("image_manifest"), // { hero, exterior[], interiors, amenities, floorPlans[], gallery[] }
  // SEO (auto-generated by Octypo v2)
  seo: json("seo"), // { title, description, ogImage, schema }
  // Analytics
  views: integer("views").default(0),
  leads: integer("leads").default(0),
  // Metadata
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
  publishedAt: timestamp("published_at"),
});

export const insertMiniSiteSchema = createInsertSchema(miniSites).omit({ id: true, createdAt: true, updatedAt: true, views: true, leads: true });
export type MiniSite = typeof miniSites.$inferSelect;
export type InsertMiniSite = z.infer<typeof insertMiniSiteSchema>;

// =====================
// Prospect Imports
// =====================
export const prospects = pgTable("prospects", {
  id: varchar("id").primaryKey(),
  fileName: text("file_name").notNull(),
  fileType: text("file_type").notNull(), // pdf, zip, ppt
  fileUrl: text("file_url").notNull(),
  fileHash: text("file_hash"), // SHA-256 hash for duplicate detection
  status: text("status").default("processing"), // processing, ready, published, failed
  // Error recovery fields
  processingCheckpoint: text("processing_checkpoint"), // Last successful step: extracting, mapping, translating, etc.
  lastError: text("last_error"), // Error message from last failure
  retryCount: integer("retry_count").default(0), // Number of retry attempts
  // Extracted content
  extractedText: text("extracted_text"),
  extractedImages: json("extracted_images"), // [{ url, page, alt }]
  extractedTables: json("extracted_tables"), // [{ headers, rows }]
  // AI-Classified images (from Vision API)
  classifiedImages: json("classified_images"), // [{ url, category, role, quality, description, ... }]
  imageManifest: json("image_manifest"), // { hero, exterior[], interiors, amenities, floorPlans[], gallery[] }
  // Generated content
  generatedTitle: text("generated_title"),
  generatedDescription: text("generated_description"),
  generatedSections: json("generated_sections"), // Structured content blocks
  // Output
  miniSiteId: varchar("mini_site_id"), // Created mini-site UUID
  miniSiteSlug: text("mini_site_slug"), // Created mini-site slug for URL navigation
  projectId: varchar("project_id"), // Created project UUID
  projectSlug: text("project_slug"), // Created project slug for URL navigation
  // Metadata
  uploadedBy: varchar("uploaded_by"),
  createdAt: timestamp("created_at").defaultNow(),
  processedAt: timestamp("processed_at"),
}, (table) => ({
  fileHashIdx: index("prospects_file_hash_idx").on(table.fileHash),
  statusIdx: index("prospects_status_idx").on(table.status),
}));

export const insertProspectSchema = createInsertSchema(prospects).omit({ id: true, createdAt: true, processedAt: true });
export type Prospect = typeof prospects.$inferSelect;
export type InsertProspect = z.infer<typeof insertProspectSchema>;

// =====================
// Templates
// =====================
export const templates = pgTable("templates", {
  id: varchar("id").primaryKey(),
  name: text("name").notNull(),
  type: text("type").notNull(), // page, mini-site, project
  description: text("description"),
  thumbnail: text("thumbnail"),
  structure: json("structure"), // Template structure/layout
  defaultContent: json("default_content"), // Default placeholder content
  isSystem: boolean("is_system").default(false), // System template vs user template
  createdAt: timestamp("created_at").defaultNow(),
});

export const insertTemplateSchema = createInsertSchema(templates).omit({ id: true, createdAt: true });
export type Template = typeof templates.$inferSelect;
export type InsertTemplate = z.infer<typeof insertTemplateSchema>;

// =====================
// Global Areas
// =====================
export const globalAreas = pgTable("global_areas", {
  id: varchar("id").primaryKey(),
  name: text("name").notNull(), // header, footer, sidebar
  type: text("type").notNull(),
  content: json("content"), // Area content blocks
  settings: json("settings"), // Display settings
  isActive: boolean("is_active").default(true),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const insertGlobalAreaSchema = createInsertSchema(globalAreas).omit({ id: true, updatedAt: true });
export type GlobalArea = typeof globalAreas.$inferSelect;
export type InsertGlobalArea = z.infer<typeof insertGlobalAreaSchema>;

// =====================
// Languages / i18n
// =====================
export const languages = pgTable("languages", {
  id: varchar("id").primaryKey(),
  code: text("code").notNull().unique(), // he, en, ar, ru
  name: text("name").notNull(),
  nativeName: text("native_name").notNull(),
  direction: text("direction").default("ltr"), // ltr, rtl
  isDefault: boolean("is_default").default(false),
  isActive: boolean("is_active").default(true),
});

export const insertLanguageSchema = createInsertSchema(languages).omit({ id: true });
export type Language = typeof languages.$inferSelect;
export type InsertLanguage = z.infer<typeof insertLanguageSchema>;

// =====================
// Translations
// =====================
export const translations = pgTable("translations", {
  id: varchar("id").primaryKey(),
  entityType: text("entity_type").notNull(), // page, project, mini-site
  entityId: varchar("entity_id").notNull(),
  languageCode: text("language_code").notNull(),
  field: text("field").notNull(), // title, description, content, etc
  value: text("value"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const insertTranslationSchema = createInsertSchema(translations).omit({ id: true, createdAt: true, updatedAt: true });
export type Translation = typeof translations.$inferSelect;
export type InsertTranslation = z.infer<typeof insertTranslationSchema>;

// =====================
// Pages (CMS Pages)
// =====================
export const pages = pgTable("pages", {
  id: varchar("id").primaryKey(),
  title: text("title").notNull(),
  slug: text("slug").notNull().unique(),
  status: text("status").default("draft"), // draft, active, hidden
  parentId: varchar("parent_id"),
  order: integer("order").default(0),
  templateId: varchar("template_id"),
  content: json("content"), // JSON content blocks
  seo: json("seo"), // { title, description, ogImage }
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const insertPageSchema = createInsertSchema(pages).omit({ id: true, createdAt: true, updatedAt: true });
export type Page = typeof pages.$inferSelect;
export type InsertPage = z.infer<typeof insertPageSchema>;

// =====================
// Media Library
// =====================
export const media = pgTable("media", {
  id: varchar("id").primaryKey(),
  name: text("name").notNull(),
  type: text("type").notNull(), // image/jpeg, video/mp4, etc
  url: text("url").notNull(),
  thumbnailUrl: text("thumbnail_url"),
  size: integer("size").default(0),
  altText: text("alt_text"),
  folder: text("folder"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const insertMediaSchema = createInsertSchema(media).omit({ id: true, createdAt: true });
export type Media = typeof media.$inferSelect;
export type InsertMedia = z.infer<typeof insertMediaSchema>;

// =====================
// Site Settings
// =====================
export const settings = pgTable("settings", {
  id: varchar("id").primaryKey(),
  key: text("key").notNull().unique(),
  value: json("value"),
  category: text("category"), // general, seo, social, contact
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const insertSettingsSchema = createInsertSchema(settings).omit({ id: true, updatedAt: true });
export type Settings = typeof settings.$inferSelect;
export type InsertSettings = z.infer<typeof insertSettingsSchema>;

// =====================
// Site Settings (Single Row)
// =====================
export const siteSettings = pgTable("site_settings", {
  id: text("id").primaryKey().default("main"), // Single row with 'main' as default
  brandName: text("brand_name"),
  email: text("email"),
  phone: text("phone"),
  address: text("address"),
  website: text("website"),
  logoUrl: text("logo_url"),
  socialInstagram: text("social_instagram"),
  socialFacebook: text("social_facebook"),
  socialLinkedin: text("social_linkedin"),
  socialWhatsapp: text("social_whatsapp"),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const insertSiteSettingsSchema = createInsertSchema(siteSettings).omit({ id: true, updatedAt: true });
export type SiteSettings = typeof siteSettings.$inferSelect;
export type InsertSiteSettings = z.infer<typeof insertSiteSettingsSchema>;

// =====================
// Projects (Real Estate)
// =====================
export const projects = pgTable("projects", {
  id: varchar("id").primaryKey(),
  slug: text("slug").unique(),
  name: text("name").notNull(),
  nameEn: text("name_en"),
  developer: text("developer").notNull(),
  developerLogo: text("developer_logo"),
  developerInfo: json("developer_info"), // { name, description, established, notableProjects[] }
  location: text("location").notNull(),
  locationEn: text("location_en"),
  coordinates: json("coordinates"), // { lat, lng }
  locationDetails: json("location_details"), // Full location with landmarks, connectivity, descriptions
  priceFrom: integer("price_from").notNull(),
  priceCurrency: text("price_currency").default("AED"),
  roiPercent: integer("roi_percent"),
  completionDate: text("completion_date"),
  propertyType: text("property_type").notNull(),
  buildingType: text("building_type"), // Tower, Villa, Townhouse
  bedrooms: text("bedrooms"),
  description: text("description"),
  descriptionEn: text("description_en"),
  tagline: text("tagline"),
  taglineEn: text("tagline_en"),
  imageUrl: text("image_url"),
  featured: boolean("featured").default(false),
  status: text("status").default("draft"), // draft, active, hidden
  // Extended content for property page
  heroImage: text("hero_image"),
  highlights: json("highlights"), // [{ icon, title, titleHe, value }]
  amenities: json("amenities"), // [{ category, items: [{ icon, name, nameHe }] }]
  amenitiesByCategory: json("amenities_by_category"), // { wellness: [...], leisure: [...], etc }
  units: json("units"), // [{ type, typeHe, sizeFrom, sizeTo, priceFrom, priceTo, view, features }]
  paymentPlan: json("payment_plan"), // { name, downPayment, duringConstruction, onHandover, milestones[] }
  gallery: json("gallery"), // [{ url, alt, type: 'image'|'video' }]
  brochureUrl: text("brochure_url"),
  neighborhood: json("neighborhood"), // { description, nearbyPlaces: [{ name, distance, type }] }
  floorPlans: json("floor_plans"), // [{ name, image, size, bedrooms }]
  faqs: json("faqs"), // [{ question, questionHe, answer, answerHe, category }]
  // NEW: Project specifications
  specs: json("specs"), // { totalFloors, totalUnits, totalParkingSpaces, buildingHeight, architecturalStyle }
  // NEW: Investment metrics
  investmentMetrics: json("investment_metrics"), // { expectedRoiPercent, rentalYieldPercent, pricePerSqft, capitalAppreciationForecast }
  // NEW: Project status & regulatory
  projectStatus: text("project_status"), // off-plan, under-construction, ready-to-move, completed
  reraNumber: text("rera_number"),
  dldNumber: text("dld_number"),
  ownership: text("ownership"), // freehold, leasehold
  furnishing: text("furnishing"), // furnished, semi-furnished, unfurnished, shell-core
  serviceCharge: text("service_charge"),
  numberOfBuildings: integer("number_of_buildings"),
  commissionPercent: text("commission_percent"),
  launchDate: text("launch_date"),
  constructionProgress: integer("construction_progress"), // 0-100
  // NEW: Media & links
  googleMapsUrl: text("google_maps_url"),
  videoUrl: text("video_url"),
  // NEW: Tags & relations
  tags: json("tags").$type<string[]>(),
  relatedProjects: json("related_projects").$type<string[]>(),
  // Links
  templateId: varchar("template_id"),
  miniSiteId: varchar("mini_site_id"),
  prospectId: varchar("prospect_id"),
  // SEO
  seo: json("seo"), // { title, description, ogImage, schema }
  // Analytics
  views: integer("views").default(0),
  // Metadata
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
  publishedAt: timestamp("published_at"),
}, (table) => ({
  statusIdx: index("projects_status_idx").on(table.status),
  featuredIdx: index("projects_featured_idx").on(table.featured),
}));

export const insertProjectSchema = createInsertSchema(projects).omit({ id: true, createdAt: true, updatedAt: true });
export type Project = typeof projects.$inferSelect;
export type InsertProject = z.infer<typeof insertProjectSchema>;

// =====================
// Leads
// =====================
export const leads = pgTable("leads", {
  id: varchar("id").primaryKey(),
  name: text("name").notNull(),
  phone: text("phone").notNull(),
  email: text("email"),
  investmentGoal: text("investment_goal"),
  budgetRange: text("budget_range"),
  timeline: text("timeline"),
  experience: text("experience"),
  message: text("message"),
  source: text("source"), // Page or project where lead came from
  sourceType: text("source_type"), // page, project, mini-site
  sourceId: varchar("source_id"), // ID of source
  leadSource: text("lead_source").default("website"), // Marketing channel: website, facebook, instagram, google, referral, phone, whatsapp, other
  interestedProjectId: varchar("interested_project_id"), // Project ID the lead is interested in
  status: text("status").default("new"), // new, contacted, in_progress, negotiation, closed_won, closed_lost
  tags: json("tags").$type<string[]>(), // ["hot", "investor", "first-time", etc]
  priority: text("priority").default("medium"), // low, medium, high
  notes: text("notes"), // Internal notes (legacy, kept for backward compat)
  assignedTo: varchar("assigned_to"), // User ID
  nextFollowUp: timestamp("next_follow_up"), // Next scheduled follow-up date
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (table) => ({
  statusIdx: index("leads_status_idx").on(table.status),
  createdAtIdx: index("leads_created_at_idx").on(table.createdAt),
}));

export const insertLeadSchema = createInsertSchema(leads).omit({ id: true, createdAt: true, updatedAt: true });
export type Lead = typeof leads.$inferSelect;
export type InsertLead = z.infer<typeof insertLeadSchema>;

// =====================
// Lead Notes (Activity Timeline)
// =====================
export const leadNotes = pgTable("lead_notes", {
  id: varchar("id").primaryKey(),
  leadId: varchar("lead_id").notNull(),
  type: text("type").notNull(), // note, call, email, meeting, whatsapp, status_change
  content: text("content").notNull(),
  createdBy: varchar("created_by"), // User ID who created the note
  metadata: json("metadata"), // Additional data like { oldStatus, newStatus } for status changes
  createdAt: timestamp("created_at").defaultNow(),
}, (table) => ({
  leadIdIdx: index("lead_notes_lead_id_idx").on(table.leadId),
}));

export const insertLeadNoteSchema = createInsertSchema(leadNotes).omit({ id: true, createdAt: true });
export type LeadNote = typeof leadNotes.$inferSelect;
export type InsertLeadNote = z.infer<typeof insertLeadNoteSchema>;

// =====================
// Lead Reminders
// =====================
export const leadReminders = pgTable("lead_reminders", {
  id: varchar("id").primaryKey(),
  leadId: varchar("lead_id").notNull(),
  title: text("title").notNull(),
  description: text("description"),
  dueDate: timestamp("due_date").notNull(),
  isCompleted: boolean("is_completed").default(false),
  createdBy: varchar("created_by"),
  createdAt: timestamp("created_at").defaultNow(),
  completedAt: timestamp("completed_at"),
}, (table) => ({
  leadIdIdx: index("lead_reminders_lead_id_idx").on(table.leadId),
  isCompletedIdx: index("lead_reminders_is_completed_idx").on(table.isCompleted),
}));

export const insertLeadReminderSchema = createInsertSchema(leadReminders).omit({ id: true, createdAt: true, completedAt: true });
export type LeadReminder = typeof leadReminders.$inferSelect;
export type InsertLeadReminder = z.infer<typeof insertLeadReminderSchema>;

// =====================
// Site Translations (Key-Value i18n strings)
// =====================
export const siteTranslations = pgTable("site_translations", {
  key: varchar("key").primaryKey(),
  he: text("he").notNull(),
  en: text("en").notNull(),
  category: text("category"), // nav, hero, about, contact, etc.
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const insertSiteTranslationSchema = createInsertSchema(siteTranslations).omit({ updatedAt: true });
export type SiteTranslation = typeof siteTranslations.$inferSelect;
export type InsertSiteTranslation = z.infer<typeof insertSiteTranslationSchema>;

// =====================
// Contact Form Schema
// =====================
export const contactFormSchema = z.object({
  name: z.string().min(2, "שם חייב להכיל לפחות 2 תווים"),
  phone: z.string()
    .min(9, "מספר טלפון לא תקין")
    .regex(/^[\d\s\-+()]+$/, "מספר טלפון לא תקין"),
  email: z.string()
    .email("כתובת אימייל לא תקינה")
    .optional()
    .or(z.literal("")),
  investmentGoal: z.enum(["income", "appreciation", "both"]).optional(),
  budgetRange: z.string().optional(),
  timeline: z.enum(["short", "long"]).optional(),
  experience: z.enum(["first", "experienced"]).optional(),
  message: z.string().optional(),
});

export type ContactFormData = z.infer<typeof contactFormSchema>;

// =====================
// Site Stats (Dynamic Statistics)
// =====================
export const siteStats = pgTable("site_stats", {
  id: varchar("id").primaryKey(),
  key: text("key").notNull().unique(), // projects, investors, yield, experience
  value: integer("value").notNull(),
  suffix: text("suffix").notNull(), // +, %, etc
  labelHe: text("label_he").notNull(),
  labelEn: text("label_en").notNull(),
  color: text("color"), // CSS color class
  order: integer("order").default(0),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const insertSiteStatSchema = createInsertSchema(siteStats).omit({ id: true, updatedAt: true });
export type SiteStat = typeof siteStats.$inferSelect;
export type InsertSiteStat = z.infer<typeof insertSiteStatSchema>;

// =====================
// Investment Zones
// =====================
export const investmentZones = pgTable("investment_zones", {
  id: varchar("id").primaryKey(),
  name: text("name").notNull(),
  nameEn: text("name_en").notNull(),
  avgRoi: integer("avg_roi").notNull(), // stored as percentage * 10 (65 = 6.5%)
  rentalYield: integer("rental_yield").notNull(),
  appreciation: integer("appreciation").notNull(),
  demand: text("demand").notNull(), // very-high, high, medium, premium
  description: text("description").notNull(),
  descriptionEn: text("description_en").notNull(),
  coordinates: json("coordinates"), // [lat, lng]
  order: integer("order").default(0),
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const insertInvestmentZoneSchema = createInsertSchema(investmentZones).omit({ id: true, createdAt: true, updatedAt: true });
export type InvestmentZone = typeof investmentZones.$inferSelect;
export type InsertInvestmentZone = z.infer<typeof insertInvestmentZoneSchema>;

// =====================
// Case Studies
// =====================
export const caseStudies = pgTable("case_studies", {
  id: varchar("id").primaryKey(),
  investmentAmount: integer("investment_amount").notNull(), // AED
  currentValue: integer("current_value").notNull(),
  roiPercent: integer("roi_percent").notNull(),
  investmentYear: text("investment_year").notNull(),
  exitYear: text("exit_year").notNull(),
  location: text("location").notNull(),
  locationEn: text("location_en").notNull(),
  propertyType: text("property_type").notNull(),
  propertyTypeEn: text("property_type_en").notNull(),
  testimonial: text("testimonial").notNull(),
  testimonialEn: text("testimonial_en").notNull(),
  order: integer("order").default(0),
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const insertCaseStudySchema = createInsertSchema(caseStudies).omit({ id: true, createdAt: true, updatedAt: true });
export type CaseStudy = typeof caseStudies.$inferSelect;
export type InsertCaseStudy = z.infer<typeof insertCaseStudySchema>;

// =====================
// Content Blocks (CMS Content)
// =====================
export const contentBlocks = pgTable("content_blocks", {
  id: varchar("id").primaryKey(),
  section: varchar("section").notNull(), // hero, about, whyDubai, process, footer, etc.
  blockKey: varchar("block_key").notNull(), // title, subtitle, description, cta, etc.
  value: text("value"), // Hebrew content
  valueEn: text("value_en"), // English content
  contentType: varchar("content_type").default("text"), // text, richtext, image, number, json
  metadata: json("metadata"), // Additional data (icon, color, order)
  isActive: boolean("is_active").default(true),
  order: integer("order").default(0),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (table) => ({
  sectionBlockKeyIdx: index("content_blocks_section_block_key_idx").on(table.section, table.blockKey),
}));

export const insertContentBlockSchema = createInsertSchema(contentBlocks).omit({ id: true, createdAt: true, updatedAt: true });
export type ContentBlock = typeof contentBlocks.$inferSelect;
export type InsertContentBlock = z.infer<typeof insertContentBlockSchema>;

// Re-export chat models for integrations
export * from "./models/chat";
